# Generated by Django 6.0.1 on 2026-02-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='image_url',
            field=models.URLField(blank=True, help_text='Frame image URL', max_length=500, null=True),
        ),
    ]
